default:
  image: node:20.2.0

variables:
  ACKEE_VERCEL_API_TOKEN: ""
  CLIENT_VERCEL_API_TOKEN: ""

deploy_development_ackee:
  stage: deploy
  only:
    - development
  script:
    - yarn install --frozen-lockfile --global vercel
    - vercel pull --yes --environment=preview --token=$ACKEE_VERCEL_API_TOKEN
    - vercel build --token=$ACKEE_VERCEL_API_TOKEN
    - vercel deploy --prebuilt --token=$ACKEE_VERCEL_API_TOKEN

deploy_stage_ackee:
  stage: deploy
  only:
    - stage
  script:
    - yarn install --frozen-lockfile --global vercel
    - vercel pull --yes --environment=production --token=$ACKEE_VERCEL_API_TOKEN
    - vercel build --prod --token=$ACKEE_VERCEL_API_TOKEN
    - vercel deploy --prebuilt --prod --token=$ACKEE_VERCEL_API_TOKEN

deploy_production_client:
  stage: deploy
  only:
    - main
  script:
    - yarn install --frozen-lockfile --global vercel
    - vercel pull --yes --environment=production --token=$CLIENT_VERCEL_API_TOKEN
    - vercel build --prod --token=$CLIENT_VERCEL_API_TOKEN
    - vercel deploy --prebuilt --prod --token=$CLIENT_VERCEL_API_TOKEN
