default:
    image: node:20.11.1

variables:
    VERCEL_PROJECT_NAME: 'project-name'

try_build:
    stage: build
    only:
        - merge_requests
    except:
        - dev
        - main
    before_script:
        - corepack enable
        - corepack install
        - yarn install --immutable
    script:
        - yarn test:ci

deploy_development_ackee:
    stage: deploy
    only:
        - dev
    before_script:
        - corepack enable
        - corepack install
    script:
        - yarn dlx -q vercel link --project=$VERCEL_PROJECT_NAME --scope=$ACKEE_VERCEL_SCOPE --yes --token=$ACKEE_VERCEL_API_TOKEN
        - yarn dlx -q vercel pull --yes --environment=preview --token=$ACKEE_VERCEL_API_TOKEN
        - yarn dlx -q vercel build --token=$ACKEE_VERCEL_API_TOKEN
        - yarn dlx -q vercel deploy --prebuilt --token=$ACKEE_VERCEL_API_TOKEN

deploy_stage_ackee:
    stage: deploy
    only:
        - stage
    before_script:
        - corepack enable
        - corepack install
    script:
        - yarn dlx -q vercel pull --yes --environment=production --scope=$ACKEE_VERCEL_SCOPE --token=$ACKEE_VERCEL_API_TOKEN
        - yarn dlx -q vercel build --prod --token=$ACKEE_VERCEL_API_TOKEN
        - yarn dlx -q vercel deploy --prebuilt --prod --token=$ACKEE_VERCEL_API_TOKEN
