default:
    image: node:20.11.1

variables:
    VERCEL_PROJECT_NAME: 'temp-project'

.package-manager: &package-manager
    - corepack enable
    - corepack install

try_build:
    stage: build
    only:
        - merge_requests
    except:
        - dev
        - stage
        - main
    script:
        - *package-manager
        - yarn install --immutable
        - yarn test:ci



deploy_development:
    stage: deploy
    only:
        - dev
    script:
        - *package-manager
        - yarn dlx -q vercel link --project=$VERCEL_PROJECT_NAME --scope=$WEB_VERCEL_SCOPE --yes --token=$WEB_VERCEL_TOKEN
        - yarn dlx -q vercel pull --yes --scope=$WEB_VERCEL_SCOPE --token=$WEB_VERCEL_TOKEN --environment=preview
        - yarn dlx -q vercel build --token=$WEB_VERCEL_TOKEN
        - yarn dlx -q vercel deploy --prebuilt --token=$WEB_VERCEL_TOKEN

deploy_stage:
    stage: deploy
    only:
        - stage
    script:
        - *package-manager
        - yarn dlx -q vercel link --project=$VERCEL_PROJECT_NAME --scope=$WEB_VERCEL_SCOPE --yes --token=$WEB_VERCEL_TOKEN
        - yarn dlx -q vercel pull --yes --scope=$WEB_VERCEL_SCOPE --token=$WEB_VERCEL_TOKEN --environment=production
        - yarn dlx -q vercel build --prod --token=$WEB_VERCEL_TOKEN
        - yarn dlx -q vercel deploy --prebuilt --prod --token=$WEB_VERCEL_TOKEN
