compressionLevel: 0

enableHardenedMode: true

enableTelemetry: false

nmHoistingLimits: none

nodeLinker: node-modules

preferInteractive: true

defaultSemverRangePrefix: ''

networkConcurrency: 100

nmSelfReferences: false

enableInlineHunks: true
