compressionLevel: 0

defaultSemverRangePrefix: ''

enableHardenedMode: true

enableInlineHunks: true

enableTelemetry: false

networkConcurrency: 100

nmHoistingLimits: none

nmSelfReferences: false

nodeLinker: node-modules

preferInteractive: true

nmMode: hardlinks-global
