/**
 * - __This file is generated by the formatTranslations script. Do not modify it manually.__
 * - Run `yarn localize` to update this file.
 */
export default {
    'general.error': 'Něco se pokazilo. Zkuste to prosím později.',
    'general.logout': 'Odhlášení',
    'general.login': 'Přihlásit',
    'form.error.required': 'Toto pole je povinné.',
} as const;
