/**
 * - __This file is generated by the formatTranslations script. Do not modify it manually.__
 * - Run `yarn localize` to update this file.
 */
export default {
    'general.error': 'Something went wrong. Please try it later.',
    'general.logout': 'Logout',
    'general.login': 'Login',
    'form.error.required': 'This field is required.',
} as const;
